### ISSUE TITLE
Add CONTRIBUTING.md as per the project

### ISSUE THREAD

**Issue by ankitbeniwal** [ankitbeniwal/QuestCase#3]

**Comment by orama254** [comment]
Greetings

I'd be happy to take up this task

**Comment by ankitbeniwal** [comment]
@orama254 Yeah Sure. Go ahead.

**Comment by ridhikapila27** [comment]
I would really like to be a part of this task...kindly assign me. and please give a little description of your requirement

**Comment by ankitbeniwal** [comment]
@ridhikapila27 Sorry but this issue is already assigned to @orama254 on a first-come basis.
